# Generated by Django 4.2.2 on 2023-06-28 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cosecha', models.DateField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=10)),
                ('abv', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lugar', models.CharField(max_length=100)),
            ],
        ),
    ]
