version: "4"
services:
    mysql:
        image: mysql:latest
        container_name: mysql
       
        environment:
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: admin
        ports:
            - "3306:3306"
            volumes:
            - ./mysql_volume:/var/lib/mysql
