version: "4"
services:
    mysql:
        image: mysql:latest
        container_name: mysql
        restart: always
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: admin
            MYSQL_ROOT_PASSWORD: admin
        ports:
            - "3306:3306"
        expose:
            - "3306"
        volumes:
            - ./mysql_volume:/var/lib/mysql
